<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS102Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d0bc7ffb-d758-4032-949f-f3806c420e3c</testSuiteGuid>
   <testCaseLink>
      <guid>31beeb05-262c-4d4a-9a6a-78266a9d3b38</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC101Login(Sucess)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5242c5df-989a-431f-b2df-19902d86eab1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData(DB)</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>5242c5df-989a-431f-b2df-19902d86eab1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>52b6f3fb-54ac-4770-8580-8352e730eaa5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5242c5df-989a-431f-b2df-19902d86eab1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>bc50f7a4-0fa0-49fa-bca8-1e56b62dfe59</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
